layout_spectrum: 0.7349388711154461
typography_spectrum: 0.8081285657826811
color:
  brandStrength: 0.6188970599323511
  lightness: 0.9259452873375267
  saturation: 0.7573661135975271
  rhythmicContrast: 0.36063043121248484
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Top Shelf Social
