typography_spectrum: 0.8081285657826811
color:
  brandStrength: 0.6188970599323511
  lightness: 0.9259452873375267
  saturation: 0.7573661135975271
  rhythmicContrast: 0.36063043121248484
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
layout_spectrum: 0.7349388711154461
name: Top Shelf Social
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99c26d39-382d-4644-8c89-5c34708b2a0e.png
title: Let's bring Innovation to Social Media Marketing
